document.write("Hello,Javascript!!");
document.write("<br>");
document.writeln("Hello,JavaScript20201120 From VSCode!!!");
document.write("<br>");
document.writeln("Hello,JavaScript20201121 From VSCode!!!");
document.write("<br>");
document.writeln("Hello,JavaScript20201121 From ATOM!!!");
document.write("<br>");
document.writeln("Hello,JavaScript20201201 From ATOM!!!");
document.write("<br>");
document.writeln("Hello,JavaScript20201201 From Sparky iPad!!!");
document.write("<br>");
document.writeln("Hello,JavaScript20210408 From VSCode!!!");
document.write("<br>");
document.writeln("Hello,JavaScript20210408 From CLI!!!");
document.write("<br>");
document.writeln("Hello,JavaScript20210408 From VSCode!!!");
document.write("<br>");
document.writeln("Hello,JavaScript20210408 From Code-Server!!!");
